#!/bin/bash

info () {
  echo -e '\n\e[0;35m'$1'\e[0;37m\n'
}

# Install docker
info "Installing Docker and other packages"
sudo yum install -y yum-utils
sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

sudo yum -y install epel-release
sudo yum -y install docker-ce docker-ce-cli containerd.io python3 python3-pip epel-release ansible git
sudo systemctl enable docker
sudo systemctl start docker
sudo usermod -aG docker dswhitehouse

# Install kubectl
info "Installing kubectl"
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
rm kubectl

# Disable firewalld
info "Disabling the firewall"
sudo systemctl stop firewalld > /dev/null 2>&1
sudo systemctl disable firewalld > /dev/null 2>&1

# Disable swap
info "Disabling swap"
sudo /usr/sbin/swapoff -a

# Set SELinux to permissive
info "Setting SELinux to Permissive"
sudo setenforce 0
sudo sed -i 's/enforcing/permisive/g' /etc/selinux/config
